project:
  type: website
  output-dir: docs

website:
  title: "Diagnostic Information for Student Retention and Success (DMISRS) Project"
  navbar:
    left:
      - about.qmd
    right: 
    - icon: file-text
      text: Robert Noel Prince
      href: https://robertprince.github.io/


format:
  html:
    backgroundcolor: "#ADD8E6"
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true

editor: visual

